const APP={lang:localStorage.getItem('dt_lang')||'en',driver:JSON.parse(localStorage.getItem('dt_driver')||'null'),modules:[],questions:[],screen:'home',quiz:null};
const $=s=>document.querySelector(s); const app=$('#app');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
function t(en,hi){return APP.lang==='hi'?hi:en}
function toast(msg){const x=$('#toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function setLang(lang){APP.lang=lang;localStorage.setItem('dt_lang',lang);render()}
function save(){localStorage.setItem('dt_driver',JSON.stringify(APP.driver))}
async function syncDriver(){try{await fetch('/api/drivers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:APP.driver.id,name:APP.driver.name,mobile:APP.driver.mobile,license:APP.driver.license,vehicle_reg:APP.driver.vehicleReg,vehicle_model:APP.driver.vehicleModel,dealer:APP.driver.dealer,location:APP.driver.location})})}catch(e){}}
async function syncAttempt(rec){try{await fetch('/api/attempts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({attempt_id:rec.attemptId,driver_id:APP.driver.id,quiz_type:rec.quizType,score:rec.score,percentage:rec.percentage,total:rec.total,question_ids:rec.questionIds,answers:rec.answers})})}catch(e){}}
async function loadData(){
  const [m,q]=await Promise.all([fetch('data/modules.json').then(r=>r.json()),fetch('data/questions.json').then(r=>r.json())]);
  APP.modules=m.modules;APP.questions=q.questions||q;
}
function go(screen,data={}){APP.screen=screen;Object.assign(APP,data);render()}
function header(){return ''}
function home(){return `<section class="hero"><div class="hero-bg"></div><div class="hero-content"><div class="pill">TATA MOTORS • COMMERCIAL VEHICLES</div><h1>${t('Driver Training Programme','ड्राइवर प्रशिक्षण कार्यक्रम')}</h1><p>${t('Safer Drivers  |  Higher Uptime  |  Stronger India','सुरक्षित चालक  |  बेहतर अपटाइम  |  मजबूत भारत')}</p><div class="pill-row"><span class="pill">🛡️ ${t('Safe Driving','सुरक्षित ड्राइविंग')}</span><span class="pill">⚙️ ${t('Better Vehicle Care','बेहतर वाहन देखभाल')}</span><span class="pill">⛽ ${t('Higher Fuel Efficiency','बेहतर ईंधन दक्षता')}</span><span class="pill">👥 ${t('Professional Drivers','प्रोफेशनल ड्राइवर')}</span></div><button class="primary" onclick="go('register')">${t('Start Training →','प्रशिक्षण शुरू करें →')}</button></div></section>`}
function register(){const d=APP.driver||{};return `<div class="page"><div class="card registration"><h1 class="section-title">${t('Driver Registration','ड्राइवर पंजीकरण')}</h1><p class="muted">${t('Enter driver and vehicle details to continue.','आगे बढ़ने के लिए चालक और वाहन का विवरण दर्ज करें।')}</p><form id="regForm"><div class="form-grid">
<div class="field"><label>${t('Driver Name *','चालक का नाम *')}</label><input id="name" required value="${esc(d.name||'')}" placeholder="${t('Full name','पूरा नाम')}"></div>
<div class="field"><label>${t('Mobile Number *','मोबाइल नंबर *')}</label><input id="mobile" required inputmode="numeric" pattern="[0-9]{10}" maxlength="10" value="${esc(d.mobile||'')}" placeholder="10 digit mobile number"></div>
<div class="field"><label>${t('Driving Licence No.','ड्राइविंग लाइसेंस नं.')}</label><input id="license" value="${esc(d.license||'')}"></div>
<div class="field"><label>${t('Vehicle Registration No.','वाहन रजिस्ट्रेशन नं.')}</label><input id="vehicleReg" value="${esc(d.vehicleReg||'')}"></div>
<div class="field"><label>${t('Vehicle Model','वाहन मॉडल')}</label><select id="vehicleModel"><option value="">${t('Select model','मॉडल चुनें')}</option>${['Signa','Prima','Ultra','LPT','Other'].map(x=>`<option ${d.vehicleModel===x?'selected':''}>${x}</option>`).join('')}</select></div>
<div class="field"><label>${t('Dealer / Workshop','डीलर / वर्कशॉप')}</label><input id="dealer" value="${esc(d.dealer||'')}"></div>
<div class="field full"><label>${t('Location','स्थान')}</label><input id="location" value="${esc(d.location||'')}" placeholder="City / District"></div>
</div><div class="btn-row" style="margin-top:18px"><button class="primary" type="submit">${t('Continue →','आगे बढ़ें →')}</button><button class="secondary" type="button" onclick="go('home')">${t('Back','वापस')}</button></div></form></div></div>`}
function moduleProgress(id){const p=JSON.parse(localStorage.getItem('dt_progress_'+(APP.driver?.id||'none') )||'{}');return p[id]||0}
function dashboard(){if(!APP.driver)return go('register');const done=APP.modules.filter(m=>moduleProgress(m.id)>=100).length;const avg=JSON.parse(localStorage.getItem('dt_attempts_'+APP.driver.id)||'[]');const pre=avg.find(a=>a.quizType==='Pre-Test');return `<div class="page"><div class="dash-head"><div class="driver-mini"><div class="avatar">${esc((APP.driver.name||'D').slice(0,1).toUpperCase())}</div><div><h1 class="section-title">${t('Welcome, '+APP.driver.name,'स्वागत है, '+APP.driver.name)}</h1><div class="muted">${esc(APP.driver.id)} • ${esc(APP.driver.vehicleReg||'Vehicle')}</div></div></div><div class="progress-ring" style="--p:${Math.round(done/APP.modules.length*100)}"><span>${Math.round(done/APP.modules.length*100)}%</span></div></div>
<div class="stat-grid"><div class="stat"><h3>8</h3><div>${t('Training Modules','प्रशिक्षण मॉड्यूल')}</div></div><div class="stat green"><h3>${done}/8</h3><div>${t('Modules Completed','पूर्ण मॉड्यूल')}</div></div><div class="stat"><h3>${pre?pre.percentage+'%':'—'}</h3><div>${t('Pre-Test Score','प्री-टेस्ट स्कोर')}</div></div></div>
<div class="assessment-grid"><div class="assessment pre"><h2>${t('Pre-Test','प्री-टेस्ट')}</h2><p class="muted">10 questions • 100 marks • randomized</p><button class="primary" onclick="startQuiz('Pre-Test')">${t('Start Pre-Test →','प्री-टेस्ट शुरू करें →')}</button></div><div class="assessment final"><h2>${t('Final Assessment','फाइनल असेसमेंट')}</h2><p class="muted">20 questions • 100 marks • 30 minutes</p><button class="primary" onclick="startQuiz('Final Assessment')">${t('Start Final Assessment →','फाइनल असेसमेंट शुरू करें →')}</button></div></div>
<h2>${t('Training Modules','प्रशिक्षण मॉड्यूल')}</h2><div class="module-grid">${APP.modules.map(m=>{const p=moduleProgress(m.id);return `<div class="module-card" onclick="go('lesson',{moduleId:'${m.id}',lessonIndex:0})"><div class="module-icon">${m.icon}</div><h3>${t(m.title,m.titleHi)}</h3><div class="muted small">${t(m.summary,m.summaryHi)}</div><div class="progress" style="margin-top:10px"><i style="width:${p}%"></i></div><div class="module-status">${p>=100?t('Completed','पूर्ण'):p>0?t('In progress','प्रगति में'):t('Not started','शुरू नहीं हुआ')}</div></div>`}).join('')}</div>
<div class="btn-row" style="margin-top:20px"><button class="secondary" onclick="go('history')">${t('Driver History','ड्राइवर इतिहास')}</button><button class="secondary" onclick="go('admin')">${t('Trainer / MIS','ट्रेनर / MIS')}</button></div></div>`}
function lesson(){const m=APP.modules.find(x=>x.id===APP.moduleId);if(!m)return go('dashboard');const i=APP.lessonIndex||0;const s=m.sections[i];return `<div class="page"><div class="lesson"><div class="lesson-header"><div><div class="muted">${t('Training Module','प्रशिक्षण मॉड्यूल')}</div><h1 class="section-title">${t(m.title,m.titleHi)}</h1><p class="muted">${t(m.summary,m.summaryHi)}</p></div><button class="secondary" onclick="go('dashboard')">← ${t('Dashboard','डैशबोर्ड')}</button></div><div class="card lesson-section"><h2>${t(s.title,s.titleHi)}</h2><ul>${s.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></div><div class="lesson-nav"><button class="secondary" ${i===0?'disabled':''} onclick="go('lesson',{moduleId:'${m.id}',lessonIndex:${i-1}})">← ${t('Previous','पिछला')}</button><div class="muted">${i+1} / ${m.sections.length}</div><button class="primary" onclick="nextLesson('${m.id}',${i})">${i===m.sections.length-1?t('Complete Module →','मॉड्यूल पूर्ण करें →'):t('Next →','आगे →')}</button></div></div></div>`}
function nextLesson(id,i){if(i>=APP.modules.find(m=>m.id===id).sections.length-1){const p=JSON.parse(localStorage.getItem('dt_progress_'+APP.driver.id)||'{}');p[id]=100;localStorage.setItem('dt_progress_'+APP.driver.id,JSON.stringify(p));toast(t('Module completed','मॉड्यूल पूर्ण'));go('dashboard')}else go('lesson',{moduleId:id,lessonIndex:i+1})}
function normalizeModule(q){const m=q.module; if(m==='Driving Technique'||m==='Fuel Economy')return 'fuel';if(m==='Vehicle Maintenance')return 'maintenance';if(['BS6 Knowledge','BS6 Driver Actions','Instrument Cluster'].includes(m))return 'bs6';if(m==='Tata Samarth')return 'samarth';if(m==='Emergency & Driver Safety')return 'emergency';if(m==='Vehicle Familiarisation')return 'vehicle';if(m==='Road Signs')return 'road-signs';return 'road-safety'}
const finalDist={'road-safety':4,'road-signs':3,'emergency':2,'vehicle':2,'fuel':3,'maintenance':2,'bs6':3,'samarth':1};
function historyIds(){const a=JSON.parse(localStorage.getItem('dt_attempts_'+APP.driver.id)||'[]');return a.flatMap(x=>x.questionIds||[]).slice(-40)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function allocateServer(type,count){try{const r=await fetch('/api/quiz/allocate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({driver_id:APP.driver.id,quiz_type:type,count,vehicle_model:APP.driver.vehicleModel||''})});if(r.ok)return await r.json()}catch(e){}return null}
async function startQuiz(type){if(!APP.driver)return go('register');const count=type==='Final Assessment'?20:10;const server=await allocateServer(type,count);let qs=server?.questions;if(!qs){let pool=APP.questions.filter(q=>q.active!==false);const recent=new Set(historyIds());const fresh=pool.filter(q=>!recent.has(q.id));pool=(fresh.length>=count?fresh:pool);if(type==='Final Assessment'){qs=[];for(const [mod,n] of Object.entries(finalDist)){const p=shuffle(pool.filter(q=>normalizeModule(q)===mod));qs.push(...p.slice(0,n))}if(qs.length<count){const used=new Set(qs.map(q=>q.id));qs.push(...shuffle(pool.filter(q=>!used.has(q.id))).slice(0,count-qs.length))}}else{qs=shuffle(pool).slice(0,count)}}
APP.quiz={type,questions:qs.map(q=>typeof q==='string'?APP.questions.find(x=>x.id===q):q),index:0,answers:[],started:Date.now()};go('quiz')}
function quiz(){const q=APP.quiz.questions[APP.quiz.index];const total=APP.quiz.questions.length;const chosen=APP.quiz.answers[APP.quiz.index];return `<div class="page"><div class="quiz-wrap"><div class="quiz-meta"><div><b>${t(APP.quiz.type,APP.quiz.type==='Pre-Test'?'प्री-टेस्ट':'फाइनल असेसमेंट')}</b><div class="muted">${t('Question','प्रश्न')} ${APP.quiz.index+1} / ${total}</div></div><span class="badge">${esc(q.difficulty)}</span></div><div class="progress"><i style="width:${((APP.quiz.index)/total)*100}%"></i></div><div class="q-card" style="margin-top:14px"><div class="q-number">${esc(q.id)} • ${esc(q.topic)}</div><h2>${esc(t(q.question.en,q.question.hi))}</h2>${q.options[APP.lang].map((o,i)=>`<label class="option"><input type="radio" name="opt" value="${i}" ${chosen===i?'checked':''}><span><b>${'ABCD'[i]}.</b> ${esc(o)}</span></label>`).join('')}<div class="btn-row" style="margin-top:20px"><button class="primary" onclick="submitAnswer()">${APP.quiz.index===total-1?t('Finish →','समाप्त →'):t('Next →','आगे →')}</button>${APP.quiz.index>0?'<button class="secondary" onclick="prevQ()">← '+t('Previous','पिछला')+'</button>':''}</div></div></div></div>`}
function submitAnswer(){const el=document.querySelector('input[name="opt"]:checked');if(!el){toast(t('Please select an answer','कृपया उत्तर चुनें'));return}APP.quiz.answers[APP.quiz.index]=Number(el.value);if(APP.quiz.index===APP.quiz.questions.length-1)finishQuiz();else{APP.quiz.index++;render()}}
function prevQ(){APP.quiz.index--;render()}
function finishQuiz(){const qs=APP.quiz.questions;let correct=0;qs.forEach((q,i)=>{if(APP.quiz.answers[i]===q.correctAnswer)correct++});const percentage=Math.round(correct/qs.length*100);const rec={attemptId:'ATT-'+Date.now(),quizType:APP.quiz.type,dateTime:new Date().toISOString(),questionIds:qs.map(q=>q.id),score:correct*5,percentage,correct,total:qs.length,answers:APP.quiz.answers,moduleIds:qs.map(normalizeModule)};const key='dt_attempts_'+APP.driver.id;const arr=JSON.parse(localStorage.getItem(key)||'[]');arr.push(rec);localStorage.setItem(key,JSON.stringify(arr.slice(-50)));if(APP.quiz.type==='Final Assessment')localStorage.setItem('dt_final_'+APP.driver.id,JSON.stringify(rec));syncAttempt(rec);go('result',{result:rec})}
function result(){const r=APP.result;const passed=r.percentage>=80;return `<div class="page"><div class="card result"><div style="font-size:55px">${passed?'✓':'●'}</div><h1>${t('Assessment Complete','असेसमेंट पूर्ण')}</h1><div class="score-big">${r.percentage}%</div><p class="muted">${r.correct} / ${r.total} ${t('correct','सही')}</p><div class="meter"><i style="width:${r.percentage}%"></i></div><div class="result-grid"><div class="result-box"><b>${r.correct}</b><div class="small">${t('Correct','सही')}</div></div><div class="result-box"><b>${r.total-r.correct}</b><div class="small">${t('Incorrect','गलत')}</div></div><div class="result-box"><b>${r.total}</b><div class="small">${t('Total','कुल')}</div></div></div><p>${r.quizType==='Final Assessment'?(passed?t('Assessment threshold: 80% (app rule).','असेसमेंट थ्रेशोल्ड: 80% (ऐप नियम)।'):t('Assessment threshold: 80% (app rule). Review the learning modules and retry.','असेसमेंट थ्रेशोल्ड: 80% (ऐप नियम)। मॉड्यूल दोबारा देखें और पुनः प्रयास करें।')):t('Pre-test is diagnostic and is used to establish the starting level.','प्री-टेस्ट प्रारंभिक स्तर जानने के लिए है।')}</p><div class="btn-row" style="justify-content:center"><button class="primary" onclick="go('dashboard')">${t('Continue Training','प्रशिक्षण जारी रखें')}</button><button class="secondary" onclick="go('history')">${t('View History','इतिहास देखें')}</button></div></div></div>`}
function history(){const a=JSON.parse(localStorage.getItem('dt_attempts_'+APP.driver.id)||'[]').reverse();const prog=JSON.parse(localStorage.getItem('dt_progress_'+APP.driver.id)||'{}');return `<div class="page"><div class="card history"><div class="dash-head"><div><h1 class="section-title">${t('Driver Training History','ड्राइवर प्रशिक्षण इतिहास')}</h1><p class="muted">${esc(APP.driver.name)} • ${esc(APP.driver.id)}</p></div><button class="secondary" onclick="go('dashboard')">← ${t('Dashboard','डैशबोर्ड')}</button></div><h2>${t('Training Progress','प्रशिक्षण प्रगति')}</h2><table><thead><tr><th>${t('Module','मॉड्यूल')}</th><th>${t('Status','स्थिति')}</th><th>${t('Progress','प्रगति')}</th></tr></thead><tbody>${APP.modules.map(m=>{const p=prog[m.id]||0;return `<tr><td>${t(m.title,m.titleHi)}</td><td><span class="badge ${p>=100?'ok':'pending'}">${p>=100?t('Completed','पूर्ण'):p?t('In progress','प्रगति में'):t('Pending','लंबित')}</span></td><td>${p}%</td></tr>`}).join('')}</tbody></table><h2 style="margin-top:25px">${t('Attempt History','अटेम्प्ट इतिहास')}</h2><table><thead><tr><th>Type</th><th>Score</th><th>Date</th><th>Questions</th></tr></thead><tbody>${a.length?a.map(x=>`<tr><td>${esc(x.quizType)}</td><td>${x.percentage}%</td><td>${new Date(x.dateTime).toLocaleString()}</td><td>${x.total}</td></tr>`).join(''):'<tr><td colspan="4" class="muted">No attempts yet.</td></tr>'}</tbody></table><div class="btn-row" style="margin-top:18px"><button class="primary" onclick="go('certificate')">${t('Certificate / Completion','सर्टिफिकेट / पूर्णता')}</button></div></div></div>`}
function certificate(){const final=JSON.parse(localStorage.getItem('dt_final_'+APP.driver.id)||'null');const complete=APP.modules.every(m=>moduleProgress(m.id)>=100);return `<div class="page"><div class="certificate"><img src="assets/logo.png" alt="Tata Motors" style="height:55px"><div class="muted">COMMERCIAL VEHICLES</div><h1>${t('Driver Training Certificate','ड्राइवर प्रशिक्षण प्रमाणपत्र')}</h1><p>${t('This is a locally generated completion view for the training application.','यह प्रशिक्षण एप्लिकेशन के लिए स्थानीय रूप से तैयार किया गया पूर्णता प्रमाणपत्र है।')}</p><h2>${esc(APP.driver.name)}</h2><p>${esc(APP.driver.id)} • ${esc(APP.driver.vehicleReg||'')}</p><p>${complete?'Training modules completed':'Complete all training modules to mark completion'}${final?` • Final Assessment ${final.percentage}%`:''}</p><p class="small">Certificate ID: CERT-${APP.driver.id}-${new Date().getFullYear()}</p><div class="btn-row" style="justify-content:center"><button class="primary" onclick="window.print()">${t('Print / Save PDF','प्रिंट / PDF सेव करें')}</button><button class="secondary" onclick="go('history')">${t('Back','वापस')}</button></div></div></div>`}
function admin(){const all=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('dt_attempts_')){try{all.push(...JSON.parse(localStorage.getItem(k)||'[]'))}catch{}}}const drivers=APP.driver?[APP.driver]:[];const avg=all.length?Math.round(all.reduce((s,x)=>s+x.percentage,0)/all.length):0;return `<div class="page"><div class="dash-head"><div><h1 class="section-title">${t('Trainer / MIS Dashboard','ट्रेनर / MIS डैशबोर्ड')}</h1><p class="muted">${t('Step 6 • Centralised data architecture with local demo persistence','स्टेप 6 • लोकल डेमो डेटा के साथ केंद्रीकृत डेटा आर्किटेक्चर')}</p></div><button class="secondary" onclick="go('dashboard')">← ${t('Dashboard','डैशबोर्ड')}</button></div><div class="admin-grid"><div class="admin-card"><strong>${drivers.length}</strong><div>${t('Current Driver','वर्तमान चालक')}</div></div><div class="admin-card"><strong>${all.length}</strong><div>${t('Attempts Stored','संग्रहीत प्रयास')}</div></div><div class="admin-card"><strong>${avg}%</strong><div>${t('Average Score','औसत स्कोर')}</div></div><div class="admin-card"><strong>${navigator.onLine?'Online':'Offline'}</strong><div>${t('Connectivity','कनेक्टिविटी')}</div></div></div><div class="card"><h2>${t('Final Assessment Distribution','फाइनल असेसमेंट वितरण')}</h2><div class="dist">${Object.entries(finalDist).map(([m,n])=>`<div class="dist-row"><span>${t(APP.modules.find(x=>x.id===m)?.title||m,APP.modules.find(x=>x.id===m)?.titleHi||m)}</span><b>${n}</b></div>`).join('')}</div><p class="small muted" style="margin-top:14px">${t('Production deployment: connect the included FastAPI service to PostgreSQL and use server-side allocation for multi-device trainer operations.','प्रोडक्शन डिप्लॉयमेंट: शामिल FastAPI सर्विस को PostgreSQL से जोड़ें और मल्टी-डिवाइस संचालन के लिए सर्वर-साइड प्रश्न आवंटन उपयोग करें।')}</p></div></div>`}
function render(){document.documentElement.lang=APP.lang;$('#langEn').classList.toggle('active',APP.lang==='en');$('#langHi').classList.toggle('active',APP.lang==='hi');if(APP.screen==='home')app.innerHTML=home();else if(APP.screen==='register')app.innerHTML=register();else if(APP.screen==='dashboard')app.innerHTML=dashboard();else if(APP.screen==='lesson')app.innerHTML=lesson();else if(APP.screen==='quiz')app.innerHTML=quiz();else if(APP.screen==='result')app.innerHTML=result();else if(APP.screen==='history')app.innerHTML=history();else if(APP.screen==='certificate')app.innerHTML=certificate();else if(APP.screen==='admin')app.innerHTML=admin()}
document.addEventListener('submit',e=>{if(e.target.id!=='regForm')return;e.preventDefault();APP.driver={id:APP.driver?.id||('TM-DRV-'+Date.now().toString().slice(-8)),name:$('#name').value.trim(),mobile:$('#mobile').value.trim(),license:$('#license').value.trim(),vehicleReg:$('#vehicleReg').value.trim(),vehicleModel:$('#vehicleModel').value,dealer:$('#dealer').value.trim(),location:$('#location').value.trim(),createdAt:APP.driver?.createdAt||new Date().toISOString()};save();syncDriver();go('dashboard')});
$('#langEn').onclick=()=>setLang('en');$('#langHi').onclick=()=>setLang('hi');$('#trainerBtn').onclick=()=>go(APP.driver?'admin':'register');
(async()=>{try{await loadData();render()}catch(e){app.innerHTML='<div class="page"><div class="card"><h2>Module load error</h2><p>Please run the package through a local web server (not file://).</p></div></div>'}})();
