services:
  - type: web
    name: tata-dtm-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DTM_APP_KEY
        value: DTM_DRIVER_PUBLIC_V1
      - key: DTM_ADMIN_KEY
        generateValue: true
